var data = {
    "products": [
        {
            id : 1,
            "description" : "",
            "price" : "",
            "discount-price" : "",
            "img-path" : ""
        },
        // beverages
        {
            id : 100,
            "description" : "",
            "price" : "",
            "discount-price" : "",
            "img-path" : ""
        },
        // appetizers
        {
            id : 200,
            title : "Guacomole Dip",
            "description" : "Our finest avocado selection made to the best combination",
            "price" : "3.99",
            "discount-price" : "",
            "img-path" : "images/appetizer/guacamole.jpg"
        },
        {
            id : 201,
            title : "Bean Dip",
            "description" : "Fried beans covered with our finest cheese dip",
            "price" : "4.49",
            "discount-price" : "",
        },
        {
            id : 202,
            title : "Small Cheese Dip",
            "description" : "Great for the kids",
            "price" : "3.49",
            "discount-price" : "",
        },
        {
            id : 203,
            title : "Large Cheese Dip",
            "description" : "Adult servings",
            "price" : "6.29",
            "discount-price" : "",
        },
        {
            id : 204,
            title : "Nachos & Cheese",
            "description" : "Nachos, topped with cheese and served with beef or chicken",
            "price" : "5.29",
            "discount-price" : "",
        },
        {
            id : 205,
            title : "Tex-Mex Nachos",
            "description": "Nachos with beans, cheese and jalape&ntilde;os",
            "price" : "5.29",
            "discount-price" : "",
        },        
        {
            id : 206,
            title : "Nachos Grilled",
            "description" : "Nachos grilled with chorizo (Mexican sausage)",
            "price" : "7.99",
            "discount-price" : "",
        },
        {
            id : 207,
            title : "Choriqueso",
            "description" : "Cheese dip with chorizo (Mexican sausage)",
            "price" : "5.99",
            "discount-price" : "",
        },
        {
            id: 208,
            title: "Cheese Quesadilla",
            "description": "Plain cheese quesadilla",
            "price": "2.29",
            "discount-price": "",
        },
        {
            id: 209,
            title: "Cheese Quesadilla",
            "description": "With steak or grilled chicken",
            "price": "4.29",
            "discount-price": "",
        },
        {
            id: 210,
            title: "Cheese Quesadilla",
            "description": "With mushrooms",
            "price": "3.29",
        },
        {
            id: 211,
            title: "Cheese Quesadilla",
            "description": "With ground beef or marinated chicken",
            "price": "3.29",
        },
        {
            id: 212,
            title: "Cheese Quesadilla",
            "description": "with Spinach",
            "price": "3.29",
        },
        {
            id: 213,
            title: "Guacamole Salad",
            "description": "Crisp lettuce, tomatoes, guacamole, and croutons",
            "price": "4.99",
        },
        {
            id: 214,
            title: "Tossed Salad",
            "description": "Crisp lettuce, diced tomateos, onions, bell peppers, cheese, and croutons",
            "price": "3.29",
        },
        {
            id: 215,
            title: "Grilled Chicken or Steak Salad",
            "description": "On top a bed of crisp lettuce, tomatoes, onions, bell peppers, and cheese",
            "price": "6.99",
        },
        {
            id: 216,
            title: "Order of grilled Chicken or Steak",
            "description": "Plain grilled chicken or steak",
            "price": "5.99",
        },
        // side orders
        {
            id: 300,
            title: "Street Tacos",
            "description": "Grilled steak, chicken, chorizo, pork. Served with chopped onions and cilantro",
            "price": "2.99 EA",
        },
        {
            id: 301,
            title: "Taco",
            "description": "your choice of marinated chicken or beef, soft or crispy filled with lettuce and cheese",
            "price": "1.99",
        },
        {
            id: 302,
            title: "Taco",
            "description": "With grilled chicken or grilled steak",
            "price": "2.99",
        },
        {
            id: 303,
            title: "Enchilada",
            "description": "Your Choise of beef, chicken, or cheese topped with special sauce",
            "price": "1.99",
        },
        {
            id: 304,
            title: "Burrito",
            "description": "Your Choise of chicken, beans, or beef topped with special sauce",
            "price": "3.49",
        },
        {
            id: 305,
            title: "Chile Relleno",
            "description": "Topped with a special sauce",
            "price": "3.45",
        },
        {
            id: 306,
            title: "Tamale",
            "description": "Topped with ground beef and mild red sauce",
            "price": "3.49",
        },
        {
            id: 307,
            title: "Tostadas",
            "description": "Flat corn tortillas covered with ground beef, lettuce, tomatoes, and sour cream",
            "price": "3.99",
        },
        {
            id: 308,
            title: "Chimichanga a la Carte",
            "description": "Ground beef or Marinated Chicken",
            "price": "3.99",
        }, 
        {
            id: 309,
            title: "Chimichanga a la Carte",
            "description": "Grilled Steak or Chicken",
            "price": "4.99",
        },
        {
            id: 310,
            title: "Pico de Gallo",
            "description": "Diced jalape&ntilde;o peppers, onions, tomato, and cilantro with a tangy lemon taste",
            "price": "1.05",
        },
        {
            id: 311,
            title: "Sour Cream",
            "description": "Dip in sour cream",
            "price": "1.05",
        },
        {
            id: 312,
            title: "Jalape&ntilde;o Peppers",
            "description": "Jalape&ntilde;o Peppers",
            "price": "1.05",
        },
        {
            id: 313,
            title: "Tortillas",
            "description": "Flour or corn tortilla",
            "price": "1.05",
        },
        {
            id: 314,
            title: "Mexican Rice",
            "description": "Mexican Rice",
            "price": "1.99",
        },
        {
            id: 315,
            title: "Refried Beans",
            "description": "Refried Beans",
            "price": "1.99",
        },
        // kids menu 
        {
            id: 400,
            title: "Enchilada",
            "description": "Served with rice and beans",
            "price": "4.99",
        },
        {
            id: 401,
            title: "Burrito",
            "description": "Served with rice and beans",
            "price": "4.99",
        },
        {
            id: 402,
            title: "Taco",
            "description": "Served with rice and beans",
            "price": "4.99",
        },
        {
            id: 403,
            title: "Quesadilla",
            "description": "Served with rice and beans",
            "price": "4.99",
        },
        {
            id: 404,
            title: "Hamburger or Cheeseburger",
            "description": "Served with lettuce, tomate, sour cream and Fries",
            "price": "4.99",
        },
        {
            id: 405,
            title: "Chicken Fingers",
            "description": "Served with Fries",
            "price": "4.99",
        },
        {
            id: 406,
            title: "Cheese Fingers",
            "description": "Served with Fries",
            "price": "4.99",
        },
        // fajitas
        {
            id: 500,
            title: "Fajita Mushroom",
            "description": "For the vegetarian, Topped with melted cheese",
            "price": "9.99",
        },
        {
            id: 501,
            isNew : true,
            title: "Fajita Potato",
            "description": "Baked potato with grilled chicken or steak, bell pepper, tomato, onions and covered with cheese sauce, make it double for only $ 22.99",
            "price": "22.99",
        },
        {
            id: 502,
            title: "Fajita Steak, Chicken or Combo",
            "description": "Make it double for only $22.99",
            "price": "11.99",
        },
        {
            id: 503,
            title: "Shrimp Fajita",
            "description": "Make it double for only $23.99",
            "price": "12.99",
        },
        {
            id: 504,
            title: "Fajita Jalisco",
            "description": "Tender strips of chicken, beef skirt steak, and shrimp, make it double for only $23.99",
            "price": "12.99",
        },
        {
            id: 505,
            title: "Fajita Tres Camino's",
            "description": "Steak, chicken, shrimp, chorizo and Mexican sausage, make it double for only $25.99",
            "price": "13.99",
        },
        {
            id: 506,
            title: "Vallarta Fajita",
            "description": "Imitation crab meat, grilled chicken, steak, and shrimp cooked with fresh pineapple, bell pepper, tomato and onions. Make it double for $25.99",
            "price": "13.99",
        },
    ],
    "locations": {
        "paris" : {
            "location" : "PARIS",
            "street" : "E Jasper 508",
            "city" : "Paris",
            "zipcode" : "61944",
            "state" : "IL",
            "phone" : "70810320123",
            hours : 'SUN - THR 10:00AM - 9:00PM <br> FRI - SAT 10:00AM - 10:00PM',
            maindishes : [1],
            beverages: [100],
            fajitas : [500,501,502,503,504,505,506],
            kids : [400,401,402,403,404,405,406],
            sideOrders : [300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315],
            appetizers : [200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216]
        },
        //"paris2" : {
        //    "location" : "PARIS",
        //    "street" : "E Jasper 508",
        //    "city" : "Paris",
        //    "zipcode" : "61944",
        //    "state" : "IL",
        //    "phone" : "70810320123",
        //    hours : 'SUN - THR 10:00AM - 9:00PM <br> FRI - SAT 10:00AM - 10:00PM',
        //    maindishes : [1],
        //    beverages : [100],
        //    appetizers: [200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216]
        //}
    }
}